version: '3.8'

services:
  # 1. Redis Caching Service (Chạy nội bộ trong Docker Compose)
  redis:
    image: redis:7-alpine
    container_name: local_redis
    networks:
      - ecommerce_local_net

  # 2. RabbitMQ Message Queue Service
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: local_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce_local_net

  # 3. Backend Express.js
  backend:
    build:
      context: ./ecommerce_backend
      dockerfile: Dockerfile
    container_name: local_backend
    ports:
      - "5000:5000"
    env_file:
      - ./ecommerce_backend/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    networks:
      - ecommerce_local_net

  # 4. Background Worker (Consumer)
  worker:
    build:
      context: ./ecommerce_backend
      dockerfile: Dockerfile
    container_name: local_worker
    command: ["node", "worker.js"]
    env_file:
      - ./ecommerce_backend/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    networks:
      - ecommerce_local_net

  cron_worker:
    build:
      context: ./ecommerce_backend
      dockerfile: Dockerfile
    container_name: local_cron
    command: ["node", "cron.js"]
    env_file:
      - ./ecommerce_backend/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    networks:
      - ecommerce_local_net


  # 5. Static Admin Web Panel Vue 3 (Chạy cổng 80, ghi đè cấu hình local Nginx)
  admin_web:
    build:
      context: ./ecommerce_admin_FE
      dockerfile: Dockerfile
    container_name: local_admin_web
    ports:
      - "80:80"
    volumes:
      # Ghi đè file default.conf của nginx trong container bằng cấu hình local không SSL
      - ./ecommerce_admin_FE/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - ecommerce_local_net

networks:
  ecommerce_local_net:
    driver: bridge

